stages:
  - setup
  - test

variables:
  ENVIRONMENT: "production"
  DAZN_PASSWORD: "55555e"

before_script:
  - python -m venv venv
  - . venv/Scripts/activate
  - pip install -r requirements.txt

setup:
  stage: setup
  script:
    - echo "Setup complete"

test:
  stage: test
  script:
    - pytest -k "PPVFlow" -n=2 --dashboard --html=report.html
