image: python:3.8

stages:
  - install_dependencies
  - run_tests

variables:
  DAZN_PASSWORD: ${DAZN_PASSWORD}

install_dependencies:
  stage: install_dependencies
  script:
    - pip install -r requirements.txt


run_tests:
  stage: run_tests
  script:
    - export DAZN_PASSWORD=$DAZN_PASSWORD  # Set environment variable for the current job
    - pytest -k "test_nonsigneduser" -s
