image: python:3.8

stages:
  - run_tests

variables:
  DAZN_PASSWORD: ${DAZN_PASSWORD}

run_tests:
  stage: run_tests
  script:
    - apt-get update -qy
    - apt-get install -y xvfb
    - export DISPLAY=:10

    # Change directory to the project root using GitLab CI environment variable
    - cd $CI_PROJECT_DIR

    # Create and activate a virtual environment
    - python -m venv venv
    - source venv/bin/activate  # Use 'source' for activation on Linux

    # Upgrade pip and install dependencies in the virtual environment
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install pytest
    - pip install seleniumbase  # Install SeleniumBase
    - pip install chromedriver-autoinstaller  # Install Chromedriver

    # Run a simple check to ensure the virtual environment is working
    - python -c "import sys; print(sys.prefix)"
    - python -c "import sys; print(sys.executable)"
    - python --version

    # Run the specified test with a visible browser
    - pytest tests/test_paywall_end_to_end.py --headed