stages:
  - setup
  - test

variables:
  ENVIRONMENT: "production"
  DAZN_PASSWORD: "55555e"

before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-venv  # Install Python and venv

  - python3 -m venv venv
  - . venv/bin/activate
  - pip install -r requirements.txt

setup:
  stage: setup
  script:
    - echo "Setup complete"

test:
  stage: test
  script:
    - pytest -k "PPVFlow" -n=2 --dashboard --html=report.html
