image: python:3.8

stages:
  - install_dependencies
  - run_tests

variables:
  DAZN_PASSWORD: ${DAZN_PASSWORD}

install_dependencies:
  stage: install_dependencies
  script:
    - pip install -r requirements.txt
    - pip install pytest

run_tests:
  stage: run_tests
  script:
    - apt-get update -qy
    - apt-get install -y xvfb
    - export DISPLAY=:10
    - Xvfb :10 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
    - pip install seleniumbase  # Install SeleniumBase
    - pip install chromedriver-autoinstaller  # Install Chromedriver
    - pytest -k "test_paywallNonSignedUser" -s
